[project]
name = "mcp-prompt-templates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anyio>=4.10.0",
    "mcp>=1.13.1",
    "pyyaml>=6.0.2",
]
